name: Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
      environment_url:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
      CLOUDFLARE_ACCOUNT_ID:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to ${{ inputs.environment_name }}
    environment:
      name: ${{ inputs.environment_name }}
      url: ${{ startsWith(inputs.environment_url, 'http') && inputs.environment_url || format('https://{0}', inputs.environment_url) }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          # 使用传入的唯一名称来下载正确的工件
          name: ${{ inputs.artifact_name }}
          path: public/

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "latest"
          command: deploy --env ${{ inputs.environment_name }}

      - name: Validate Deployment
        run: |
          echo "Waiting 15s for deployment to propagate..."
          sleep 15
          
          # Ensure URL has https:// protocol
          URL="${{ inputs.environment_url }}"
          if [[ ! "$URL" =~ ^https?:// ]]; then
            URL="https://$URL"
          fi
          
          echo "Running validation tests on $URL"
          SITE_URL="$URL" ./scripts/test-deployment.sh